"""add_exam_and_exam_question_tables

Revision ID: c233b732f127
Revises: 842d900434e1
Create Date: 2026-03-20 15:20:46.919066

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "c233b732f127"
down_revision: Union[str, None] = "842d900434e1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "exams",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=300), nullable=False),
        sa.Column("course", sa.String(length=200), nullable=True),
        sa.Column("exam_date", sa.Date(), nullable=True),
        sa.Column("time_limit_minutes", sa.Integer(), nullable=True),
        sa.Column("allowed_aids", sa.Text(), nullable=True),
        sa.Column("instructions", sa.Text(), nullable=True),
        sa.Column("passing_percentage", sa.Float(), nullable=False),
        sa.Column("total_points", sa.Float(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("language", sa.String(length=10), nullable=False),
        sa.Column("institution_id", sa.Integer(), nullable=False),
        sa.Column("created_by", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('draft', 'finalized', 'exported')", name="check_exam_status"
        ),
        sa.ForeignKeyConstraint(["created_by"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(
            ["institution_id"], ["institutions.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_exams_created_by"), "exams", ["created_by"], unique=False)
    op.create_index(op.f("ix_exams_id"), "exams", ["id"], unique=False)
    op.create_index(
        op.f("ix_exams_institution_id"), "exams", ["institution_id"], unique=False
    )
    op.create_index(op.f("ix_exams_status"), "exams", ["status"], unique=False)
    op.create_table(
        "exam_questions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("exam_id", sa.Integer(), nullable=False),
        sa.Column("question_id", sa.Integer(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("points", sa.Float(), nullable=False),
        sa.Column("section", sa.String(length=100), nullable=True),
        sa.ForeignKeyConstraint(["exam_id"], ["exams.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["question_id"], ["question_reviews.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("exam_id", "position", name="uq_exam_position"),
        sa.UniqueConstraint("exam_id", "question_id", name="uq_exam_question"),
    )
    op.create_index(
        op.f("ix_exam_questions_exam_id"), "exam_questions", ["exam_id"], unique=False
    )
    op.create_index(
        op.f("ix_exam_questions_id"), "exam_questions", ["id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_exam_questions_id"), table_name="exam_questions")
    op.drop_index(op.f("ix_exam_questions_exam_id"), table_name="exam_questions")
    op.drop_table("exam_questions")
    op.drop_index(op.f("ix_exams_status"), table_name="exams")
    op.drop_index(op.f("ix_exams_institution_id"), table_name="exams")
    op.drop_index(op.f("ix_exams_id"), table_name="exams")
    op.drop_index(op.f("ix_exams_created_by"), table_name="exams")
    op.drop_table("exams")
    # ### end Alembic commands ###
