"""add_authentication_models

Revision ID: 7786194d9cd6
Revises: b3334ed75530
Create Date: 2025-10-19 16:41:13.895164

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7786194d9cd6'
down_revision: Union[str, None] = 'b3334ed75530'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_prompts_tags', table_name='prompts', postgresql_using='gin')
    op.drop_index('idx_prompts_updated_at', table_name='prompts')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_prompts_updated_at', 'prompts', [sa.text('updated_at DESC')], unique=False)
    op.create_index('idx_prompts_tags', 'prompts', ['tags'], unique=False, postgresql_using='gin')
    # ### end Alembic commands ###

