"""add last_failed_login to users

Revision ID: 842d900434e1
Revises: 949c9f5b8da2
Create Date: 2026-03-20 09:49:20.881280

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "842d900434e1"  # pragma: allowlist secret
down_revision: Union[str, None] = "949c9f5b8da2"  # pragma: allowlist secret
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column("last_failed_login", sa.DateTime(timezone=True), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "last_failed_login")
    # ### end Alembic commands ###
