"""Add question review tables

Revision ID: b3334ed75530
Revises: 006
Create Date: 2025-10-19 15:26:44.069096

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b3334ed75530'
down_revision: Union[str, None] = '006'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('question_reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question_text', sa.Text(), nullable=False),
    sa.Column('question_type', sa.String(length=50), nullable=False),
    sa.Column('options', sa.JSON(), nullable=True),
    sa.Column('correct_answer', sa.Text(), nullable=True),
    sa.Column('explanation', sa.Text(), nullable=True),
    sa.Column('difficulty', sa.String(length=20), nullable=False),
    sa.Column('topic', sa.String(length=200), nullable=False),
    sa.Column('language', sa.String(length=10), nullable=True),
    sa.Column('source_chunks', sa.JSON(), nullable=True),
    sa.Column('source_documents', sa.JSON(), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('bloom_level', sa.Integer(), nullable=True),
    sa.Column('estimated_time_minutes', sa.Integer(), nullable=True),
    sa.Column('quality_tier', sa.String(length=1), nullable=True),
    sa.Column('review_status', sa.String(length=20), nullable=False),
    sa.Column('reviewed_by', sa.String(length=100), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('exam_id', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("review_status IN ('pending', 'approved', 'rejected', 'edited', 'in_review')", name='check_review_status'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_question_reviews_exam_id'), 'question_reviews', ['exam_id'], unique=False)
    op.create_index(op.f('ix_question_reviews_id'), 'question_reviews', ['id'], unique=False)
    op.create_index(op.f('ix_question_reviews_review_status'), 'question_reviews', ['review_status'], unique=False)
    op.create_table('review_comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('comment_text', sa.Text(), nullable=False),
    sa.Column('comment_type', sa.String(length=50), nullable=True),
    sa.Column('author', sa.String(length=100), nullable=False),
    sa.Column('author_role', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['question_reviews.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_review_comments_id'), 'review_comments', ['id'], unique=False)
    op.create_index(op.f('ix_review_comments_question_id'), 'review_comments', ['question_id'], unique=False)
    op.create_table('review_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('old_status', sa.String(length=20), nullable=True),
    sa.Column('new_status', sa.String(length=20), nullable=True),
    sa.Column('changed_fields', sa.JSON(), nullable=True),
    sa.Column('changed_by', sa.String(length=100), nullable=False),
    sa.Column('change_reason', sa.Text(), nullable=True),
    sa.Column('changed_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['question_reviews.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_review_history_id'), 'review_history', ['id'], unique=False)
    op.create_index(op.f('ix_review_history_question_id'), 'review_history', ['question_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_review_history_question_id'), table_name='review_history')
    op.drop_index(op.f('ix_review_history_id'), table_name='review_history')
    op.drop_table('review_history')
    op.drop_index(op.f('ix_review_comments_question_id'), table_name='review_comments')
    op.drop_index(op.f('ix_review_comments_id'), table_name='review_comments')
    op.drop_table('review_comments')
    op.drop_index(op.f('ix_question_reviews_review_status'), table_name='question_reviews')
    op.drop_index(op.f('ix_question_reviews_id'), table_name='question_reviews')
    op.drop_index(op.f('ix_question_reviews_exam_id'), table_name='question_reviews')
    op.drop_table('question_reviews')
    # ### end Alembic commands ###

