"""add_question_generation_jobs

Revision ID: d74c69d53df6
Revises: d715210cb3a3
Create Date: 2026-03-18 13:53:47.659853

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "d74c69d53df6"  # pragma: allowlist secret
down_revision: Union[str, None] = "d715210cb3a3"  # pragma: allowlist secret
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "question_generation_jobs",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("task_id", sa.String(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_question_generation_jobs_task_id"),
        "question_generation_jobs",
        ["task_id"],
        unique=True,
    )
    op.drop_column("institutions", "subscription_type")
    op.drop_column("institutions", "institution_type")
    op.drop_index(op.f("ix_subscriptions_billing_owner_id"), table_name="subscriptions")
    op.drop_constraint(
        op.f("subscriptions_billing_owner_id_fkey"), "subscriptions", type_="foreignkey"
    )
    op.drop_column("subscriptions", "billing_owner_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "subscriptions",
        sa.Column("billing_owner_id", sa.INTEGER(), autoincrement=False, nullable=True),
    )
    op.create_foreign_key(
        op.f("subscriptions_billing_owner_id_fkey"),
        "subscriptions",
        "users",
        ["billing_owner_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.create_index(
        op.f("ix_subscriptions_billing_owner_id"),
        "subscriptions",
        ["billing_owner_id"],
        unique=False,
    )
    op.add_column(
        "institutions",
        sa.Column(
            "institution_type",
            sa.VARCHAR(length=50),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.add_column(
        "institutions",
        sa.Column(
            "subscription_type",
            sa.VARCHAR(length=50),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.drop_index(
        op.f("ix_question_generation_jobs_task_id"),
        table_name="question_generation_jobs",
    )
    op.drop_table("question_generation_jobs")
    # ### end Alembic commands ###
