"""
RAG Service (Core Package Placeholder)

This is a placeholder for the Core package.
Full RAG functionality is available in the Premium package.
"""

from typing import List, Dict, Any, Optional
from pydantic import BaseModel, Field
from uuid import UUID


class RAGQuestion(BaseModel):
    """Question generated by RAG"""

    question: str
    answer: str
    difficulty: str = "medium"
    bloom_level: str = "understand"
    points: int = 1
    explanation: Optional[str] = None


class RAGContext(BaseModel):
    """Context used for RAG generation"""

    document_id: UUID
    chunk_text: str
    relevance_score: float


class RAGExamRequest(BaseModel):
    """Request for RAG-based exam generation"""

    document_ids: List[UUID]
    num_questions: int = Field(default=10, ge=1, le=50)
    difficulty: str = "mixed"
    question_types: List[str] = ["multiple_choice", "open_ended"]


class RAGExamResponse(BaseModel):
    """Response from RAG exam generation"""

    questions: List[RAGQuestion]
    contexts: List[RAGContext]
    metadata: Dict[str, Any] = {}


class RAGServicePlaceholder:
    """
    Placeholder RAG Service for Core Package

    Raises NotImplementedError for all RAG operations.
    Premium package provides full RAG functionality with Claude API.
    """

    async def generate_exam(
        self, request: RAGExamRequest, user_id: Optional[str] = None
    ) -> RAGExamResponse:
        raise NotImplementedError(
            "RAG-based exam generation is only available in the Premium package. "
            "Please upgrade to use AI-powered question generation with document context."
        )

    async def generate_questions_from_context(
        self, context: str, num_questions: int = 5, difficulty: str = "medium"
    ) -> List[RAGQuestion]:
        raise NotImplementedError(
            "RAG question generation is only available in the Premium package."
        )


# Singleton instance
rag_service = RAGServicePlaceholder()
